click: 10

wait: 45

limit: 1

link: 'https://www.pinksale.finance/launchpad/0x05eE8F679680A429c005E63AC41142aB6B43eD61?chain=BSC'

firefox: 'C:\Users\client\AppData\Local\Mozilla Firefox\firefox.exe'

chrome: 'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe'

edge: 'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe'

opera: ''

brave: 'C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe'